#pragma once

#define GLM_FORCE_RADIANS
#define VIEWPORT_WIDTH_INITIAL 1280
#define VIEWPORT_HEIGHT_INITIAL 720

#define NUM_ITERATIONS 8

#define WORLD_UP_VECTOR glm::vec3(0.0f, 1.0f, 0.0f)

#define ENABLE_MULTISAMPLING

#define EPSILON 0.00005f

#define INTERNODE_SCALE 0.03f
